Fixed Helm test connection

diff --git a/charts/memgraph-high-availability/templates/tests/test-connection.yaml b/charts/memgraph-high-availability/templates/tests/test-connection.yaml
--- a/charts/memgraph-high-availability/templates/tests/test-connection.yaml
+++ b/charts/memgraph-high-availability/templates/tests/test-connection.yaml
@@ -1,3 +1,4 @@
+# Inspect logs of this test with kubectl logs -l app=memgraph-ha-test-connection
 apiVersion: batch/v1
 kind: Job
 metadata:
@@ -8,22 +9,31 @@ metadata:
     "helm.sh/hook": test
 spec:
   template:
+    metadata:
+      labels:
+        app: memgraph-ha-test-connection
     spec:
       containers:
       - name: memgraph-test
-        image: memgraph/memgraph:2.17.0
-        command: ["/bin/sh", "-c"]
+        image: memgraph/memgraph:2.18.0
+        command: ["/bin/bash", "-c"]
         args:
           - |
-            echo "Running connection test on data instances..."
-            echo "RETURN 0;" | mgconsole --host memgraph-data-0.default.svc.cluster.local --port 7687
-            echo "RETURN 0;" | mgconsole --host memgraph-data-1.default.svc.cluster.local --port 7687
-
-            echo "Running a connection test on coordinator instances..."
-            echo "SHOW INSTANCES;" | mgconsole --host memgraph-coordinator-1.default.svc.cluster.local --port 7687
-            echo "SHOW INSTANCES;" | mgconsole --host memgraph-coordinator-2.default.svc.cluster.local --port 7687
-            echo "SHOW INSTANCES;" | mgconsole --host memgraph-coordinator-3.default.svc.cluster.local --port 7687
-
+            commands=(
+              "echo 'SHOW INSTANCES;' | mgconsole --host memgraph-coordinator-1.default.svc.cluster.local --port 7687"
+              "echo 'SHOW INSTANCES;' | mgconsole --host memgraph-coordinator-2.default.svc.cluster.local --port 7687"
+              "echo 'SHOW INSTANCES;' | mgconsole --host memgraph-coordinator-3.default.svc.cluster.local --port 7687"
+              "echo 'RETURN 0;' | mgconsole --host memgraph-data-0.default.svc.cluster.local --port 7687"
+              "echo 'RETURN 0;' | mgconsole --host memgraph-data-1.default.svc.cluster.local --port 7687"
+            )
+            for command in "${commands[@]}"; do
+              echo "Running command: $command"
+              eval $command
+              if [ $? -ne 0 ]; then
+                echo "Command failed: $command"
+                exit 1
+              fi
+            done
+            exit 0
 
       restartPolicy: Never
-  backoffLimit: 3
